#!/bin/bash

FILES="/home/decypher/micke/data/clinf/reindeer/*/*.fastq"
for f in $FILES; do
name=${f/fastq/blastn}
dc_run -parameters /home/decypher/micke/tera-blastn-ml -query $f -database vrl > $name;wait
gzip $f;wait
gzip $name;wait
done
