#!/bin/bash

FILES="/home/decypher/micke/data/clinf/reindeer/170424/*.fa"
for f in $FILES; do
name=${f/fa/blastn}
dc_run -parameters /home/decypher/micke/tera-blastn-ml -query $f -database nt > $name;wait
gzip $f;wait
gzip $name;wait
done
