#!/bin/bash

if [[ -z $1 ]]; then
	echo "Use: 'splitfasta gz' or 'splitfasta fastq'"
	exit 0
fi 
FILES=$PWD/*.$1
for f in ${FILES}; do
	if [[ ! -f  "$f" ]]; then
		echo "No $1-files in the current directory!"
		exit 0
	fi
done
nr=0
nr_of_files=$(ls *.$1|wc -l)
for f in ${FILES}; do
	if [[ "$1" == "gz" ]]; then
		u=gunzip ${f}; wait
	else
		u=${f}
	fi
	nr=$((nr+1))
	echo -en 'Processing file: '${nr}'/'${nr_of_files}\\r
	b=$(dirname "$u")/vrl_blastn/$(basename "$u")
	b=${b/fastq/blastn}
	split_fasta.py -b ${b} -f ${u};wait
	basename=${u##*/}
	hitname=$PWD'/hits_'${basename/fastq/fa}
	mv ${hitname} $PWD/vrlhits
	gzip $PWD/vrlhits/$(basename "$hitname");wait
	rm $PWD'/nohits_'${basename/fastq/fa};wait
	rm $PWD'/'${basename/fastq/fa};wait
done
