#!/bin/bash
#set -ueo pipefail

# ==============================================================================
# V-pipe Automated Pipeline: Alignment, Variant Calling, Annotation, & Dashboard
# Usage: ./vpipe_auto.sh [AF_THRESHOLD] (Default: 0.01)
# ==============================================================================

# 1. Configuration & Parameters
MIN_AF=${1:-0.01}
MIN_DP=100
REF_FASTA="references/reference.fasta"
REF_GFF="references/reference.gff3"

# Dynamically extract REFERENCE_ID from FASTA header (e.g., >IAV_H5N1_PB2 -> IAV_H5N1)
if [ -f "$REF_FASTA" ]; then
    REFERENCE_ID=$(grep ">" "$REF_FASTA" | head -n 1 | cut -d'_' -f1,2 | sed 's/^>//')
else
    REFERENCE_ID="Unknown_Virus"
fi

SNPEFF_CONFIG="snpeff.config"
WORKING_DIR=$(pwd)

echo "--- Starting Pipeline Analysis for $REFERENCE_ID ---"

echo "Threshold: AF > $MIN_AF, DP > $MIN_DP"

# 2. Step 1: Map sequences using Symbolic Links with Clean Filenames
# Note: Using 'raw_data' to match your attached script's structure
echo "--- Step 1: Mapping and cleaning filenames in raw_data folders ---"
mkdir -p samples
for f in fa/*; do
    [ -e "$f" ] || continue
    filename=$(basename "$f")
    
    # Extract components from Illumina format
    sample_id=$(echo "$filename" | cut -d'_' -f1)
    s_tag=$(echo "$filename" | cut -d'_' -f2)
    
    # Identify if it is Read 1 or Read 2
    # Vi söker efter "_R1" följt av antingen en punkt (.) eller ett understreck (_)
    if [[ "$filename" =~ _R1[._] ]]; then
        read_pair="R1"
    elif [[ "$filename" =~ _R2[._] ]]; then
        read_pair="R2"
    else
        echo "Varning: Kunde inte identifiera R1/R2 för $filename. Hoppar över."
        continue
    fi
    
    # Construct the cleaned filename
    new_filename="${sample_id}_${s_tag}_${read_pair}.fastq.gz"
    
    # Create the required subfolder structure
    target_dir="$WORKING_DIR/samples/$sample_id/$s_tag/raw_data"
    mkdir -p "$target_dir"
    
    # Create symbolic link
    ln -sf "$WORKING_DIR/$f" "$target_dir/$new_filename"
    echo "  Mapped: $filename -> $new_filename"
done

# --- Step 2: SnpEff Environment Auto-Setup & Rebuild ---
echo "--- Step 2: Recreating SnpEff Configuration and Database ---"

# 2a. Skapa en helt ny snpeff.config för detta REFERENCE_ID
# Vi rensar bort den gamla och skriver en ny från grunden
cat <<EOF > "$SNPEFF_CONFIG"
# SnpEff configuration file (Auto-generated by vpipe_auto.sh)
data.dir = ./snpeff_db

# Definiera genomet baserat på variabeln REFERENCE_ID
$REFERENCE_ID.genome : $REFERENCE_ID
EOF

# 2b. Rensa gammal databas och förbered mappar
rm -rf "snpeff_db/$REFERENCE_ID"
mkdir -p "snpeff_db/$REFERENCE_ID"

# Kopiera in referensfiler
cp "$REF_FASTA" "snpeff_db/$REFERENCE_ID/sequences.fa"
cp "$REF_GFF" "snpeff_db/$REFERENCE_ID/genes.gff"

# ... fortsätt sedan med snpEff build som vanligt
mkdir -p logs
#. ~/miniforge3/bin/activate V-pipe

# Rebuild the database (Redirecting to log to keep terminal clean)
snpEff build -c "$SNPEFF_CONFIG" -gff3 -noCheckCds -noCheckProtein -v "$REFERENCE_ID" > logs/snpeff_build.log 2>&1
echo "  - SnpEff database rebuilt. Log: logs/snpeff_build.log"

# 4. Step 3: Run V-pipe Core Workflow
echo "--- Step 3: Running V-pipe ---"
./vpipe --jobs 2 --cores 16 

# 5. Step 4: Annotation & Quality Filtering
echo "--- Step 4: Annotation & Filtering ---"
find results -name "snvs.vcf" | while read -r vcf; do
    sample_dir=$(dirname "$vcf")
    sample_name=$(echo "$vcf" | cut -d'/' -f2)
    s_folder=$(echo "$vcf" | cut -d'/' -f3)
    
    annotated_vcf="${vcf%.vcf}.annotated.vcf"
    final_vcf="${vcf%.vcf}.final.vcf"
    
    summary_html="$sample_dir/snpEff_summary.html"

    echo "Processing: $sample_name ($s_folder)"

    # Annotation: Clean command (build flags are excluded)
    snpEff -c "$SNPEFF_CONFIG" \
           -s "$summary_html" \
           "$REFERENCE_ID" "$vcf" > "$annotated_vcf"

    # Quality Filtering using bcftools
    bcftools filter -i "AF > $MIN_AF && DP > $MIN_DP" "$annotated_vcf" > "$final_vcf"
    count=$(awk '!/^#/{c++} END{print c+0}' "$final_vcf")
    echo "  - Result: $count high-confidence variants."
done

# 6. Step 5: Generating Results Dashboard (Flat version for single segment)
echo "--- Step 5: Generating Dashboard ---"
DASHBOARD_FILE="results/dashboard.html"

cat <<EOF > "$DASHBOARD_FILE"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>V-pipe Segment Dashboard</title>
    <style>
        body { font-family: sans-serif; margin: 0; display: flex; height: 100vh; background: #f8f9fa; }
        #sidebar { width: 350px; background: #2c3e50; color: white; overflow-y: auto; display: flex; flex-direction: column; }
        #sidebar h2 { padding: 20px; margin: 0; background: #1a252f; font-size: 1.1em; text-align: center; }
        .sample-link {
            padding: 12px 20px; border-bottom: 1px solid #34495e; cursor: pointer;
            display: flex; justify-content: space-between; align-items: center;
            text-decoration: none; color: #ecf0f1; font-size: 0.85em;
        }
        .sample-link:hover { background: #34495e; }
        .sample-link.active { background: #3498db; font-weight: bold; }
        .badge { background: #e67e22; padding: 2px 7px; border-radius: 8px; font-size: 0.8em; font-weight: bold; }
        #viewer { flex-grow: 1; display: flex; flex-direction: column; }
        iframe { width: 100%; height: 100%; border: none; background: white; }
        .msg { padding: 50px; text-align: center; color: #7f8c8d; }
    </style>
</head>
<body>
    <div id="sidebar">
        <h2>🔬 Segment Analysis</h2>
        <div id="menu">
EOF

find results -name "snvs.final.vcf" | sort | while read -r vcf_path; do
    s_id=$(echo "$vcf_path" | cut -d'/' -f2)
    s_t=$(echo "$vcf_path" | cut -d'/' -f3)
    rel_html="${s_id}/${s_t}/visualization/snv_calling.html"
    v_count=$(awk '!/^#/{c++} END{print c+0}' "$vcf_path")
    echo "            <a class=\"sample-link\" onclick=\"load(this, '$rel_html')\">
                <span>$s_id ($s_t)</span>
                <span class=\"badge\">$v_count var</span>
            </a>" >> "$DASHBOARD_FILE"
done

cat <<EOF >> "$DASHBOARD_FILE"
        </div>
    </div>
    <div id="viewer">
        <div id="welcome" class="msg">
            <h2>Workflow Complete</h2>
            <p>Select a sample to view the interactive SNV plot.</p>
        </div>
        <iframe id="frame" src="about:blank"></iframe>
    </div>
    <script>
        function load(el, path) {
            document.getElementById('welcome').style.display = 'none';
            document.getElementById('frame').src = path;
            document.querySelectorAll('.sample-link').forEach(l => l.classList.remove('active'));
            el.classList.add('active');
        }
    </script>
</body>
</html>
EOF
